# Generated by Django 4.2.6 on 2023-11-05 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suggested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('beatmap_link', models.CharField(max_length=255)),
                ('pp', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('mods', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('star_rating', models.FloatField()),
                ('length', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
            options={
                'verbose_name_plural': 'Suggested',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('beatmap_link', models.CharField(max_length=255)),
                ('pp', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('mods', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('star_rating', models.FloatField()),
                ('length', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
            ],
            options={
                'verbose_name_plural': 'Scores',
            },
        ),
    ]
