# Generated by Django 4.2.6 on 2023-10-31 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omap', '0002_omap_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omap',
            old_name='title',
            new_name='name',
        ),
    ]
